workflows:
  default-workflow:
    name: Kolne App Production APK
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      flutter: 3.24.5
      java: 17
    scripts:
      - name: Recreate Android Fully
        script: |
          rm -rf android
          flutter create . --platforms=android
          flutter pub get
          flutter doctor -v
      - name: Build Debug APK
        script: |
          flutter build apk --debug
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
