workflows:
  default-workflow:
    name: Kolne App Production APK
    max_build_duration: 15
    instance_type: mac_mini_m1
    environment:
      flutter: stable
    triggering:
      events:
        - push
    scripts:
      - name: Force Recreate Native Core Layout
        script: |
          echo "Purging old fragments..."
          rm -rf android
          rm -rf ios
          flutter create . --platforms android --project-name=kolne_app
      - name: Compile Fast Package Bundle
        script: |
          echo "Building binary executable..."
          flutter build apk --debug --no-pub
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
