name: kolne_real
description: Kolne - Real Bharat App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.5+9
  video_player: ^2.8.2
  image_picker: ^1.0.7
  shared_preferences: ^2.2.2
  share_plus: ^8.0.2
  audioplayers: ^6.0.0
  cupertino_icons: ^1.0.2

flutter:
  uses-material-design: true
