name: Generate Flutter Layout
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Recreate Android Directory
        run: |
          rm -rf android
          flutter create . --platforms android
      - name: Commit & Push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@://github.com'
          git add android/
          git commit -m "Fix: Automated generation of android native platform folder"
          git push origin main
